### ISSUE TITLE
git doesn't fetch new tags

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#388]
On 2.1 VM:
```
fatal: ambiguous argument 'rel_4.0.1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
From https://github.com/UCL/STIR
   8942f4e6..2a799b93  Siemens_mCT_additions -> origin/Siemens_mCT_additions
   fd8b7555..dcfda6b1  master                -> origin/master
 * [new branch]        release_4             -> origin/release_4
 * [new branch]        release_4.0           -> origin/release_4.0
 * [new tag]           rel_4.0.0             -> rel_4.0.0
 * [new tag]           stir_rel_4.0.0        -> stir_rel_4.0.0
error: pathspec 'rel_4.0.1' did not match any file(s) known to git.
CMake Error at /home/sirfuser/devel/buildVM/builds/STIR/tmp/STIR-gitupdate.cmake:147 (message):
  Failed to checkout tag: 'rel_4.0.1'
```
_Originally posted by @rijobro in https://github.com/SyneRBI/SyneRBI_VM/issues/160#issuecomment-623390728_

**Comment by KrisThielemans** [comment]
same problem when using  `origin/rel_4.0.1` in `version_config.cmake`.

**Comment by KrisThielemans** [comment]
@rijobro wrote
> I ran git fetch --tags earlier (didn't think to create a snapshot, sorry) and then compilation was fine and all ctests passed.

I suppose you ran this in `sources/STIR`?

According to the [CMake doc](https://cmake.org/cmake/help/latest/module/ExternalProject.html) I think this should work. However, they do recommend using the hash.

@rijobro or @johannesmayer could you try to set `STIR_TAG` in `version_config.cmake` to a hash that it doesn't have yet, and see if that works (I guess you'll have to start from a new VM if you didn't snapshot)

**Comment by rijobro** [comment]
> I suppose you ran this in sources/STIR?

By hash, you mean the hash of the commit? I'm fairly sure that would work, probably so would the branch name (`release_4`). I'll confirm tomorrow.

**Comment by KrisThielemans** [comment]
Branch name is dangerous according to their doc, although `origin/release_4` might work. However, that branch is moving, so that's no solution.

let's try the hash. of course, then we'd have to do the same for the others.

weird though

**Comment by KrisThielemans** [comment]
I've created https://gitlab.kitware.com/cmake/cmake/-/issues/20677.

@rijobro @johannesmayer could you please try this such that we can move on?

**Comment by rijobro** [comment]
Do you mean try with a specific commit hash?

If so, @johannesmayer (since I know you just downloaded a fresh VM), could you try:
```
cd ~/devel/SIRF-SuperBuild
git remote add rijobro https://github.com/rijobro/SIRF-SuperBuild
update_VM.sh -s -r -t rijobro/update_STIR_branch
```

**Comment by KrisThielemans** [comment]
not sure what hash you used there but 4.0.1 is f67923cf0fe11f373eb1dd965f336072570776f6

**Comment by rijobro** [comment]
Sorry i used most recent on release_4 branch. Updated now. The above code doesn't need to be changed, Johannes.

**Comment by johannesmayer** [comment]
ok the 

> Do you mean try with a specific commit hash?
> 
> If so, @johannesmayer (since I know you just downloaded a fresh VM), could you try:
> 
> ```
> cd ~/devel/SIRF-SuperBuild
> git remote add rijobro https://github.com/rijobro/SIRF-SuperBuild
> update_VM.sh -s -r -t rijobro/update_STIR_branch
> ```

this has not worked for me, it says now

```
[ 91%] Performing update step for 'STIR'
fatal: bad object f67923cf0fe11f373eb1dd965f336072570776f6
From https://github.com/UCL/STIR
   8942f4e6..2a799b93  Siemens_mCT_additions -> origin/Siemens_mCT_additions
   fd8b7555..dcfda6b1  master                -> origin/master
 * [new branch]        release_4             -> origin/release_4
 * [new branch]        release_4.0           -> origin/release_4.0
 * [new tag]           rel_4.0.0             -> rel_4.0.0
 * [new tag]           stir_rel_4.0.0        -> stir_rel_4.0.0
fatal: reference is not a tree: f67923cf0fe11f373eb1dd965f336072570776f6
CMake Error at /home/sirfuser/devel/buildVM/builds/STIR/tmp/STIR-gitupdate.cmake:147 (message):
  Failed to checkout tag: 'f67923cf0fe11f373eb1dd965f336072570776f6'


```

**Comment by KrisThielemans** [comment]
sigh. can you paste/attached a lot with a bit more (possibly with `make VERBOSE=ON`)? It should show some git command hopefully.

**Comment by rijobro** [comment]
I've just got to the same place as @johannesmayer. Don't think a `make VERBOSE=ON` would help, as it's a git problem. 

Strange that from Johannes' previous comment, you can see that `rel_4.0.0` exists as a new tag, but `rel_4.0.1` doesn't. It's as if it's only doing a partial `git fetch`.

**Comment by rijobro** [comment]
ah `make VERBOSE=ON` from the SuperBuild build directory? OK.

**Comment by johannesmayer** [comment]
the hash we use is just not on the master branch, but on the tag branch. you cannot check it out unless you do something of the kind `$ git checkout tags/<tag> -b <branch>`. that's why it will not find the hash we provide I think.

**Comment by johannesmayer** [comment]
when i do 
```
git fetch --tags
git checkout tags/stir_rel_4.0.1 -b tag-branch
git checkout f67923cf0fe11f373eb1dd965f336072570776f6
``` 
it will do the checkout.

**Comment by rijobro** [comment]
Sure. However, from your reply [further up](https://github.com/SyneRBI/SIRF-SuperBuild/issues/388#issuecomment-624188666), I guess that if we had have given it the hash (or the tag) for `rel_4.0.0`, I think it would have worked. What confuses me is why it gets `rel_4.0.0`, but not `rel_4.0.1`.

**Comment by rijobro** [comment]
Also, with `cd ~/devel/build_VM && make VERBOSE=ON`:
```
cd /home/sirfuser/devel/buildVM/sources/STIR && /usr/local/bin/cmake -P /home/sirfuser/devel/buildVM/builds/STIR/tmp/STIR-gitupdate.cmake
fatal: bad object f67923cf0fe11f373eb1dd965f336072570776f6
fatal: reference is not a tree: f67923cf0fe11f373eb1dd965f336072570776f6
CMake Error at /home/sirfuser/devel/buildVM/builds/STIR/tmp/STIR-gitupdate.cmake:147 (message):
  Failed to checkout tag: 'f67923cf0fe11f373eb1dd965f336072570776f6'
```

**Comment by rijobro** [comment]
I think updating cmake to most recent 3.17.2 (by modifying line 17 in `~/devel/CCPPETMR_VM/scripts/INSTALL_CMake.sh`) solved this problem. @johannesmayer could you confirm? I'm doing the same by going back to previous snapshot

**Comment by KrisThielemans** [comment]
aha. good idea!

**Comment by rijobro** [comment]
I've checked it twice and all seems to work, I've merged the updated version into the VM master. I've asked @johannesmayer to try with the `origin/master` SuperBuild, which uses the STIR tag. If that works, we can close https://github.com/SyneRBI/SIRF-SuperBuild/pull/394. Else, we'll merge it.

**Comment by KrisThielemans** [comment]
sounds good. thanks both!

**Comment by johannesmayer** [comment]
yes it works for me as well.
Tetris for Richard!

**Comment by KrisThielemans** [comment]
Excellent!

I'd still like to understand a bit better what happened. I see no reason why it fetched `rel_4.0.0` but not `rel_4.0.1`, certainly not why the hash didn't work.

> the hash we use is just not on the STIR master branch, but on the tag branch.

AFAIK, git hashes are not "on a branch". Neither are tags. (they are a name for a hash, not more).

>when i do
>
> git fetch --tags
> git checkout tags/stir_rel_4.0.1 -b tag-branch
> git checkout f67923cf0fe11f373eb1dd965f336072570776f6
> it will do the checkout.

I'm 99.9% confident that the checkout would have worked with just the `git fetch --tags`. I can't see why the 2nd line is relevant.

@rijobro, can you maybe post the STIR-gitupdate.cmake produced by CMake 3.17? (note that you previous one seems truncated, but i have that myself)

**Comment by KrisThielemans** [comment]
I don't know... I've updated my CMake and still have the same problem (with `rel_4.0.1` tag). I didn't start from scratch, but I cannot see why that mattered.

@rijobro @johannesmayer are you sure you tried with the tag?

**Comment by KrisThielemans** [comment]
> I'm 99.9% confident that the checkout would have worked with just the git fetch --tags. I can't see why the 2nd line is relevant.

well, I might have been confident, but I was wrong. sorry.

seems that I understand even less about `git` than I thought.

**Comment by johannesmayer** [comment]
> @rijobro @johannesmayer are you sure you tried with the tag?

Yes I ran it absolutely from scratch on the VM v2.1 and explicitly I saw in the output of the update_VM.sh that it checked out the tag `rel_4.0.1` and it does

```
sirfuser@vagrant:~/devel/buildVM/sources/STIR$ git status
HEAD detached at rel_4.0.1
nothing to commit, working tree clean
```

**Comment by KrisThielemans** [comment]
oh well. I'm 100% lost.

**Comment by KrisThielemans** [comment]
> > I'm 99.9% confident that the checkout would have worked with just the git fetch --tags. I can't see why the 2nd line is relevant.
> 
> well, I might have been confident, but I was wrong. sorry.

nope, I was right! Here's another level of confusion: I was in a branch that is associated to another remote. So, `git fetch --tags` didn't get anything from `UCL/STIR`, and so the checkout failed. But
``
git fetch --all
git checkout f67923cf0fe11f373eb1dd965f336072570776f6
```
works as expected. (The `--tags` argument is here irrelevant, as we're not using a tag but a hash).

This has little to do with CMake of course, but at least I understand git better.

**Comment by rijobro** [comment]
So, should I merge #394 or not? I only tried with the hash, not with the tag. @johannesmayer confirmed using the tag as working, so the PR shouldn't be needed. Do you agree @KrisThielemans?

**Comment by johannesmayer** [comment]
Ok now I am very confused as well.
When I come in and do `git fetch --all` it will not do the checkout afterwards. 
However `git fetch --tags` will allow me to do the checkout.

As I see it from the output down below, `git fetch --all` does fetch 

```
sirfuser@vagrant:~$ cd devel/buildVM/sources/STIR/
sirfuser@vagrant:~/devel/buildVM/sources/STIR$ git status
HEAD detached at stir_rel_4_00_alpha
nothing to commit, working tree clean
sirfuser@vagrant:~/devel/buildVM/sources/STIR$ git remote -v
origin	https://github.com/UCL/STIR (fetch)
origin	https://github.com/UCL/STIR (push)
sirfuser@vagrant:~/devel/buildVM/sources/STIR$ git fetch --all
Fetching origin
remote: Enumerating objects: 1879, done.
remote: Counting objects: 100% (1879/1879), done.
remote: Total 3243 (delta 1878), reused 1879 (delta 1878), pack-reused 1364
Receiving objects: 100% (3243/3243), 1.05 MiB | 601.00 KiB/s, done.
Resolving deltas: 100% (2619/2619), completed with 503 local objects.
From https://github.com/UCL/STIR
   8942f4e6..2a799b93  Siemens_mCT_additions -> origin/Siemens_mCT_additions
   fd8b7555..dcfda6b1  master                -> origin/master
 * [new branch]        release_4             -> origin/release_4
 * [new branch]        release_4.0           -> origin/release_4.0
 * [new tag]           rel_4.0.0             -> rel_4.0.0
 * [new tag]           stir_rel_4.0.0        -> stir_rel_4.0.0
sirfuser@vagrant:~/devel/buildVM/sources/STIR$ git checkout f67923cf0fe11f373eb1dd965f336072570776f6
fatal: reference is not a tree: f67923cf0fe11f373eb1dd965f336072570776f6
sirfuser@vagrant:~/devel/buildVM/sources/STIR$ git fetch --tags
remote: Enumerating objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 3
Unpacking objects: 100% (3/3), done.
From https://github.com/UCL/STIR
 * [new tag]           rel_4.0.1      -> rel_4.0.1
 * [new tag]           stir_rel_4.0.1 -> stir_rel_4.0.1
sirfuser@vagrant:~/devel/buildVM/sources/STIR$ git checkout f67923cf0fe11f373eb1dd965f336072570776f6
Previous HEAD position was 063cf26d updated LICENSE and VERSION for 4.0.0-alpha [ci skip]
HEAD is now at f67923cf updated VERSION.txt etc for release of version 4.0.1
sirfuser@vagrant:~/devel/buildVM/sources/STIR$ 
```


In the documentation of git fetch it says

By default, any tag that points into the histories being fetched is also fetched; the effect is to fetch tags that point at branches that you are interested in. This default behavior can be changed by using the --tags or --no-tags options or by configuring remote.<name>.tagOpt. By using a refspec that fetches tags explicitly, you can fetch tags that do not point into branches you are interested in as well.

I don't understand the histories part but does that explain to you why the rel_4.0.1 tag is not fetched?

**Comment by KrisThielemans** [comment]
> does that explain to you why the rel_4.0.1 tag is not fetched?

possibly... I've found that most people find that `git fetch` has some rather incomprehensible rules for which tags it gets, and in any case it seems to be changing with git version. Hence, specifying `--tags` is best as you're sure it's going to get them.

Seems I'll have to get a fresh VM myself. This is all pretty weird.

**Comment by johannesmayer** [comment]
> I don't understand the histories part but does that explain to you why the rel_4.0.1 tag is not fetched?

With that I meant with that is that I didn't get it, but maybe to you it was meaningful and you could maybe make sense of that sentence in contrast to me.
It looked a bit unfriendly on a second read :D , that was not intended. sorry.

**Comment by KrisThielemans** [comment]
sure. np!

In the mean time, I have confirmed that you were right, and that the `--tags` argument is necessary to be able to checkout the hash. 🤔

**Comment by rijobro** [comment]
I suppose the reason we could see `rel_4.0.0` and not `rel_4.0.1` is that `rel_4.0.0` exists along the path of a branch (`release_4.0` and `release_4`). I bet if there was a branch at the same point as the tag `rel_4.0.1`, this problem would go away.

![image](https://user-images.githubusercontent.com/33289025/81192922-b2817280-8fb2-11ea-84a6-dd41fdf72968.png)

**Comment by KrisThielemans** [comment]
I guess that's correct. I guess it's implied in the `git fetch` doc. To me, this is a CMake bug. (they should do `git fetch --all --tags` to avoid this surprising behaviour). We could possibly create a branch to work-around a CMake bug (a bit horrible, but fine). It might also disappear when `release_4` gets merged to `master`. who knows?

There's still things that puzzle me:
- why does the `git checkout hash` not work? I suppose this would get us into the murky depths of understand `git fetch`, refs and all that. In any case, not much we can do about it.
- why does upgrading CMake help for you guys, when it doesn't for me (on my VM), and in fact there's nothing in the new `STIR-gitupdate.cmake` that is different, so there's no real reason.

A thought. Did `update_VM.sh -s` by any chance update `git` as well? I see that the 2.1.0 VM comes with git 2.17.1. On my VM where I do the experiments I have git 2.26.2.

**Comment by rijobro** [comment]
The git version is still the same for me - 2.17.1.

I've attached the new `STIR-gitupdate.cmake` that seemed to work for me. You can compare it with yours to see if there are any differences.

> why does the git checkout hash not work?

For me, it did work. Do you mean why it didn't work on your VM?
[STIR-gitupdate-cmake3_17_2.cmake](https://github.com/SyneRBI/SIRF-SuperBuild/files/4587752/STIR-gitupdate-cmake3_17_2.txt)

**Comment by KrisThielemans** [comment]
> > why does the git checkout hash not work?
> 
> For me, it did work. Do you mean why it didn't work on your VM?

I meant @johannesmayer's observation of the `git`-only stuff.

**Comment by KrisThielemans** [comment]
Some more detective work why upgrading CMake works on the VM:

- Without updating CMake, `make` will "build" the `builds/STIR/stamp/STIR-update` target, which will execute `builds/STIR/tmp/STIR-gitupdate.cmake`. That fails because of the tag problem.
- With updating CMake, `make` will first build the `builds/STIR/stamp/STIR-download` target, which will execute `builds/STIR/tmp/STIR-gitclone.cmake`. That calls `rm -rf sources/STIR`, clones again, and `git checkout tag`. That works.

I'm not sure why updating CMake triggers the download (it has to be somewhere in the dependencies, but I couldn't find it), but I suppose it makes some sense: a new CMake will want to rebuild lots of stuff.

So, after all this, we've figured out that
- CMake has a bug (in my opinion) that it doesn't use `fetch --tags`, which hits us because the tag is on a branch, and for mysterious git reasons doesn't get fetched by default.
- `git checkout hash` can fail if the hash is on the remote somewhere on a branch that is not directly reachable either. This cannot be fixed by CMake as far as I can see. In any case, using the hash won't fix the problem that we see.
- by accident, upgrading CMake works-around all this because it will work from a new clone.

Summary: upgrading CMake will work. Anyone else will have this problem.

Possibly it disappears after merging the `release_4` branch into `master` in STIR, because git rules then might get the tag by default.

oh well

**Comment by KrisThielemans** [comment]
Obviously, the other thing to do is to just remove `sources/STIR` by hand.

I don't see there's anything here that we can fix. I'll leave the issue open for reference in case others get hit by hit.

**Comment by KrisThielemans** [comment]
This was raised at https://gitlab.kitware.com/cmake/cmake/-/issues/20677. (Probably) fixed in https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5389 which means this should be solved in CMake 3.20.0 or later.
